apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo-client
  labels:
    app: exo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exo-client
  template:
    metadata:
      labels:
        app: exo-client
    spec:
      containers:
      - name: my-exo-client
        image: mackkaputo/exo-client:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: exo-client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001